[project]
name = "hamelin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "diegotxegp", email = "diegotxegp@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dask[dataframe]>=2026.1.2",
    "gputil>=1.4.0",
    "hyperopt>=0.2.7",
    "ludwig>=0.17.9",
    "matplotlib>=3.11.0",
    "numpy>=2.4.6",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "pyqtgraph>=0.14.0",
    "pyside6>=6.11.1",
    "pyside6-fluent-widgets>=1.11.3",
    "pyyaml>=6.0.3",
    "ray[tune]>=2.57.0",
    "scikit-learn>=1.9.0",
    "scipy>=1.17.1",
    "xlrd>=2.0.2",
]

[project.scripts]
hamelin = "hamelin:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-qt>=4.5.0",
]
